// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Wed Mar 27 10:12:00 2024

Binary2Hex Binary2Hex_inst
(
	.w(w_sig) ,	// input  w_sig
	.x(x_sig) ,	// input  x_sig
	.y(y_sig) ,	// input  y_sig
	.z(z_sig) ,	// input  z_sig
	.a(a_sig) ,	// output  a_sig
	.b(b_sig) ,	// output  b_sig
	.c(c_sig) ,	// output  c_sig
	.d(d_sig) ,	// output  d_sig
	.e(e_sig) ,	// output  e_sig
	.f(f_sig) ,	// output  f_sig
	.g(g_sig) 	// output  g_sig
);

