// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Wed Mar 27 11:12:26 2024

lab9 lab9_inst
(
	.A(A_sig) ,	// input [7:0] A_sig
	.InA(InA_sig) ,	// input  InA_sig
	.InB(InB_sig) ,	// input  InB_sig
	.Out(Out_sig) ,	// input  Out_sig
	.Clear(Clear_sig) ,	// input  Clear_sig
	.Add_Subtract(Add_Subtract_sig) ,	// input  Add_Subtract_sig
	.Rout(Rout_sig) ,	// output [7:0] Rout_sig
	.Ccout(Ccout_sig) ,	// output [3:0] Ccout_sig
	.HEX2(HEX2_sig) ,	// output [0:6] HEX2_sig
	.HEX1(HEX1_sig) ,	// output [0:6] HEX1_sig
	.HEX0(HEX0_sig) 	// output [0:6] HEX0_sig
);

